name: Finish Hotfix

on:
  pull_request:
    branches: [master]
    types: [closed]

env:
  git_user: ${{ github.actor }}
  git_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com

jobs:
  finish-hotfix:
    if: github.event.pull_request.merged == true && (startsWith(github.head_ref, 'refs/heads/hotfix/') || startsWith(github.head_ref, 'hotfix/'))
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: false

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Initialize git config
        run: |
          git config --global user.name ${{ env.git_user }}
          git config --global user.email ${{ env.git_email }}

      - name: Finish gitflow hotfix
        id: finish-release
        uses: duplocloud/ghactions-finish-gitflow-release@master
        with:
          validate_merge: false
          delete_branch: false
          is_hotfix: true
          github_token: ${{ steps.app-token.outputs.token }}
