name: Start Hotfix

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Override hotfix version (leave blank to auto-increment patch)'
        required: false
        default: ''

env:
  git_user: duplo-bot
  git_email: devops@duplocloud.net

jobs:
  start-hotfix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: false

      - name: Get hotfix version
        id: version
        run: |
          set -euo pipefail
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "hotfix=$(echo $(sed -ne 's/^VERSION=\([0-9\.]*\).*$/\1/p' <Makefile) | awk -F. -v OFS=. '{{$NF += 1 ; print}}')" >>$GITHUB_OUTPUT
          else
            echo "hotfix=${{ github.event.inputs.version }}" >>$GITHUB_OUTPUT
          fi

      - name: Initialize git config
        run: |
          git config --global user.name $git_user
          git config --global user.email $git_email

      - name: Start gitflow hotfix
        uses: duplocloud/ghactions-start-gitflow-release@master
        with:
          github_token: ${{ secrets.DUPLO_GITHUB_TOKEN }}
          version: "${{ steps.version.outputs.hotfix }}"
          is_hotfix: true
          precommit_run: |
            set -euo pipefail
            version="${{ steps.version.outputs.hotfix }}"
            sed -e 's/^\(VERSION=\)[0-9\.]*/\1'"$version"'/g' -i Makefile
